services:

  pgrouting:
    build:
      context: pgrouting/
    ports:
      - "5432:5432"
    volumes:
      - .db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_PORT: 5432

  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - "15432:80"
    volumes:
      - .pgadmin-data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - pgrouting
    profiles:
      - pgadmin

  backend:
    build:
      context: backend/
    ports:
      - "8000:8000"
    environment:
      ENV: prod
      DATABASE_HOSTNAME: pgrouting
      DATABASE_PORT: 5432
      DATABASE_DATABASE: routing
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
    depends_on:
      - pgrouting

  frontend:
    build:
      context: frontend/
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    depends_on:
      - backend

volumes:
  db-data:
  pgadmin-data:
